# Generated by Django 5.1.4 on 2025-04-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockhistory',
            index=models.Index(fields=['stock', '-date'], name='stock_id_date_idx'),
        ),
        migrations.AddIndex(
            model_name='stockhistory',
            index=models.Index(fields=['date'], name='stockhistory_date_idx'),
        ),
    ]
